# Generated by Django 2.0.4 on 2018-04-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=45)),
                ('gravatar', models.CharField(max_length=100)),
                ('guid', models.CharField(max_length=40)),
            ],
        ),
    ]
