# Generated by Django 2.0.4 on 2018-04-27 17:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day3', '0002_personalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_training_institute', models.BooleanField()),
                ('industry_type', models.CharField(max_length=50)),
                ('website', models.URLField(max_length=100)),
                ('founded_on', models.DateField()),
                ('company_size', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('additional_contact', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_approved', models.BooleanField(default=False)),
                ('user_profile_basic_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='day3.UserProfileBasic')),
            ],
        ),
    ]
