# Generated by Django 2.0.4 on 2018-04-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day3', '0003_organizationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('banner', models.CharField(max_length=200)),
                ('audience_level', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('venue_coordinate', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('max_audience', models.IntegerField(default=0)),
                ('registration_fee', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('guid', models.CharField(max_length=40)),
                ('organization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='day3.UserProfileBasic')),
            ],
        ),
    ]
