# Generated by Django 2.0.4 on 2018-04-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day3', '0006_eventtrainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_passed', models.BooleanField(default=False)),
                ('registration_complete', models.BooleanField(default=False)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('review', models.TextField()),
                ('status', models.CharField(max_length=45)),
                ('confirmation_text', models.TextField()),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='day3.EventBasic')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='day3.UserProfileBasic')),
            ],
        ),
    ]
