# Generated by Django 2.0.4 on 2018-04-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day3', '0007_eventparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('status', models.CharField(max_length=45)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='day3.EventBasic')),
                ('profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='day3.UserProfileBasic')),
                ('trainer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='day3.UserProfileBasic')),
            ],
        ),
    ]
