# Generated by Django 2.0.4 on 2018-04-27 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day3', '0008_personalrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('salary_range', models.CharField(max_length=50)),
                ('is_parttime', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('position', models.CharField(max_length=50)),
                ('stack', models.TextField()),
                ('organization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='day3.UserProfileBasic')),
            ],
        ),
    ]
