# Generated by Django 2.0.4 on 2018-04-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day3', '0010_jobdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_passed', models.BooleanField(default=False)),
                ('call_for_interview', models.BooleanField(default=False)),
                ('screening_details', models.TextField()),
                ('job_post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='day3.JobBasic')),
            ],
        ),
    ]
