# Generated by Django 2.0.4 on 2018-04-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day3', '0011_jobapplicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbasic',
            name='guid',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
