# Generated by Django 2.0.4 on 2018-04-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day3', '0012_jobbasic_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=40)),
                ('interest', models.CharField(max_length=10)),
            ],
        ),
    ]
